### PR TITLE
Add version to Checkout get_token request

### PR DESCRIPTION
**Pull request by gudel98**

### CODE REVIEW

**Comment by gudel98** [comment]
[add version: 2.1 to checkout client](https://trello.com/c/iHgezxNw/735-add-version-21-to-checkout-client)

**Comment by ba1ash** [comment]
Hmm what if I want to send request to version '2' or '1'. Then it will be rewritten to '2.1'. Is that ok?

**Comment by gudel98** [comment]
@ba1ash As I understand, actual version is 2.1 and it's main, and we need it by default. Others were only for backward compatibility. @avsh right?

**Comment by gudel98** [comment]
@ba1ash I agree with u, it's more flexible

**Pull request merged**
